source 'https://rubygems.org'

ruby '2.1.0'
gem 'bcrypt'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'ember-data-source', '~> 1.0.0.beta.7'
gem 'ember-rails'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '4.0.4'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'

group :test do
  gem 'factory_girl_rails'
  gem 'pry'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end

group :test, :development do
  gem 'capybara'
  gem 'faker'
  gem 'launchy'
  gem 'letter_opener'
  gem 'poltergeist'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end

group :production do
  gem 'rails_12factor'
end
